spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opsbeach?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      schema: ops_user
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ops_user
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        #format_sql: true
        #show_sql: true
  application:
    name: user
  smtp:
    username: schematalabs@gmail.com
    password: pivqhzsbzohrouxp
server:
  port: 7080
  servlet:
    contextPath: /user
flyway:
  url: jdbc:postgresql://localhost:5432/opsbeach
  schemas: PUBLIC
  user: root
  password: root

management:
  endpoints:
    web:
      exposure:
        include: health
