spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    hikari:
      schema: ops_user
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ops_user
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        #format_sql: true
        #show_sql: true
  application:
    name: user
  smtp:
    username: schematalabs@gmail.com
    password: pivqhzsbzohrouxp
server:
  port: 7080
  servlet:
    contextPath: /user
flyway:
  url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
  schemas: PUBLIC
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASS}

management:
  endpoints:
    web:
      exposure:
        include: health
