application:
  connect:
    baseURL: http://localhost:7081/connect/v1/
    create-organization-node: http://localhost:7081/connect/v1/schema/organization?clientName={clientName}
  analytics:
    baseURL: https://api.aldefi.io/analytics/v1/