#stage 1
FROM maven:3.8.5 as builder

WORKDIR /app
ADD pom.xml .
ADD shared-lib/pom.xml 	./shared-lib/pom.xml
ADD user/pom.xml		./user/pom.xml
ADD connect/pom.xml		./connect/pom.xml

RUN mvn -pl shared-lib verify --fail-never
ADD shared-lib ./shared-lib
RUN mvn -pl shared-lib install

RUN mvn -pl user verify --fail-never
ADD user ./user
RUN mvn -pl shared-lib,user package

#stage 2
FROM openjdk:17
WORKDIR /user

COPY --from=builder /app/user/target/user-1.0-SNAPSHOT.jar user-1.0-SNAPSHOT.jar
EXPOSE 7083
CMD ["java", "-jar", "user-1.0-SNAPSHOT.jar"]