apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-redirect-config
  namespace: schematalabs
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: PERMANENT_REDIRECT