spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opsbeach?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      schema: analytics
  neo4j:
    uri:  bolt://localhost:7687
    authentication:
      username: neo4j
      password: neo4j@123
  data:
    neo4j:
      database: neo4j
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: analytics
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  application:
    name: analytics
  #redis:
  #  host: localhost
  #  port: 6379
  threading-future-timeout: 10000
  user:
    base-url: http://localhost:7080/user/v1/auth/
    client-register: client/register
    user-register: user/register
    user: user
    client: client
    user-login: user/login
    jwt-add: jwt
    audit: audit
    jwt-access: access
  github:
    client-id: Iv1.19e6f30a6fd55b13
    client-secret: 6543675a07cc744135a661972981c51eaca725c5
  gcloud:
    repo-bucket: "schematalabs-github-boostrap"
    file-upload-bucket: "schematalabs-file-upload-bootstrap"
    project-id: prodenv1
    location-id: us-central1
    queue-id: schematalabs-bootstrap-github
  smtp:
    username: schematalabs@gmail.com
    password: pivqhzsbzohrouxp
  security:
    oauth2:
      resource:

      client:
        registration:
          github:
            clientId: Iv1.19e6f30a6fd55b13
            clientSecret: 6543675a07cc744135a661972981c51eaca725c5
scheduler:
  enabled: true
server:
  port: 7081
  servlet:
    contextPath: /connect
  home-path: /connect/bootstrap/
  repo-storage-path: /home/surya-kumar/lakebyte/repos
flyway:
  url: jdbc:postgresql://localhost:5432/opsbeach
  schemas: PUBLIC
  user: root
  password: root

#disable neo4j health check for now
management:
  health:
    neo4j:
      enabled: false