spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: analytics
  neo4j:
    uri:  bolt://${NEO4J_HOST}:7687
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}
  data:
    neo4j:
      database: neo4j
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: analytics
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  application:
    name: analytics
  #redis:
  #  host: localhost
  #  port: 6379
  threading-future-timeout: 10000
  user:
    base-url: http://${USER_BASE_URL}:7080/user/v1/auth/
    client-register: client/register
    user-register: user/register
    user: user
    client: client
    user-login: user/login
    jwt-add: jwt
    audit: audit
    jwt-access: access
  github:
    client-id: Iv1.19e6f30a6fd55b13
    client-secret: 6543675a07cc744135a661972981c51eaca725c5
  gcloud:
    repo-bucket: "schematalabs-github-boostrap"
    file-upload-bucket: "schematalabs-file-upload-bootstrap"
    project-id: prodenv1
    location-id: us-central1
    queue-id: schematalabs-bootstrap-github
  smtp:
    username: schematalabs@gmail.com
    password: pivqhzsbzohrouxp
  security:
    oauth2:
      resource:

      client:
        registration:
          github:
            clientId: Iv1.19e6f30a6fd55b13
            clientSecret: 6543675a07cc744135a661972981c51eaca725c5
scheduler:
  enabled: true
server:
  port: 7081
  servlet:
    contextPath: /connect
  home-path: /connect/bootstrap/
  repo-storage-path: /home/surya-kumar/lakebyte/repos
flyway:
  url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
  schemas: PUBLIC
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

#disable neo4j health check for now
management:
  health:
    neo4j:
      enabled: false