spring:
  applicaton:
    name: virima
  datasource:
    url: jdbc:postgresql://34.27.156.232:5432/opsbeach?serverTimeZone=UTC&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    hikari:
      schema: virima
  neo4j:
    uri: bolt://35.238.222.192:7687
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASS}
  data:
    neo4j:
      database: neo4j
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: virima
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
  threading-future-timeout: 10000
  user:
    base-url: https://api.aldefi.io/user/v1/auth/
    client-register: client/register
    user-register: user/register
    user: user
    client: client
    user-login: user/login
    jwt-add: jwt
    audit: audit
    jwt-access: access
server:
  port: 7084
  servlet:
    contextPath: /virima
flyway:
  url: jdbc:postgresql://34.27.156.232:5432/opsbeach
  schemas: PUBLIC
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASS}

#disable neo4j health check for now
management:
  health:
    neo4j:
      enabled: false