# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: schematalabs
---
#secrets
apiVersion: v1
kind: Secret
metadata:
  name: virima-app-secret
  namespace: schematalabs
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASS: T3BzQmVAY2gxQDMk
  NEO4J_USER: bmVvNGo=
  NEO4J_PASS: bmVvNGox
---
# Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virima-app-deployment
  namespace: schematalabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: virima-app
          image: us-central1-docker.pkg.dev/prodenv1/schematalabs-virima-app/virima:tag
          ports:
            - containerPort: 7084
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: virima-app-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: virima-app-secret
                  key: POSTGRES_PASS
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: virima-app-secret
                  key: NEO4J_USER
            - name: NEO4J_PASS
              valueFrom:
                secretKeyRef:
                  name: virima-app-secret
                  key: NEO4J_PASS
---
# BackendConfig to do health check so above deployment will become ready
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-check-config-virima
  namespace: schematalabs
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 7084
    type: HTTP #case-sensitive
    requestPath: /virima/actuator/health
---
# Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: virima-app-service
  namespace: schematalabs
  annotations:
    cloud.google.com/backend-config: '{"default": "health-check-config-virima"}'
spec:
  type: ClusterIP
  selector:
    app: dev
  ports:
    - name: http
      port: 7084
      targetPort: 7084
      protocol: TCP
    - name: https
      port: 443
      targetPort: 7084
      protocol: TCP
---